import {
  PeriodUnit,
  PriceType,
  PricingTable as PricingTableType,
} from "./types";

export const PricingTable: PricingTableType = {
  id: "table-1",
  createdBy: "Ritika Sharma",
  createdAt: Date(),
  lastModifiedBy: "Ritika Sharma",
  lastModifiedAt: Date(),
  active: true,
  items: [
    {
      id: "start-plan",
      name: "Starter Plan",
      description: "A Starter Plan",
      order: 0,
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
      entitlements: ["Pocket friendly"],
    },
    {
      id: "professional-plan",
      name: "Professional Plan",
      description: "A Professional Plan",
      order: 1,
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
      entitlements: ["Still Pocket friendly"],
    },
    {
      id: "enterprise-plan",
      name: "Enterprise Plan",
      description: "A Enterprise Plan",
      order: 2,
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
      entitlements: ["Might not be Pocket friendly"],
    },
  ],
  prices: [
    {
      id: "us-day",
      item_id: "start-plan",
      name: "US DAY",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.DAY,
      amount: "99.00",
      currency: "USD",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "us-month",
      item_id: "professional-plan",
      name: "US MONTH",
      type: PriceType.RECURRING,
      period: 3,
      period_unit: PeriodUnit.WEEK,
      amount: "200.00",
      currency: "USD",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "us-year",
      item_id: "enterprise-plan",
      name: "US YEAR",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.MONTH,
      amount: "99.00",
      currency: "USD",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "eur-day",
      item_id: "start-plan",
      name: "EUR DAY",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.WEEK,
      amount: "89.00",
      currency: "EUR",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "eur-month",
      item_id: "professional-plan",
      name: "EUR MONTH",
      type: PriceType.RECURRING,
      period: 3,
      period_unit: PeriodUnit.YEAR,
      amount: "280.00",
      currency: "EUR",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "eur-year",
      item_id: "enterprise-plan",
      name: "EUR YEAR",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.WEEK,
      amount: "99.00",
      currency: "EUR",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "ind-day",
      item_id: "start-plan",
      name: "IND DAY",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.YEAR,
      amount: "999.00",
      currency: "IND",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "ind-month",
      item_id: "professional-plan",
      name: "IND MONTH",
      type: PriceType.RECURRING,
      period: 3,
      period_unit: PeriodUnit.WEEK,
      amount: "3000.00",
      currency: "IND",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
    {
      id: "ind-year",
      item_id: "enterprise-plan",
      name: "IND YEAR",
      type: PriceType.RECURRING,
      period: 40,
      period_unit: PeriodUnit.DAY,
      amount: "99.00",
      currency: "IND",
      billing_system: "chargebee",
      billing_system_id: "chargebee-id",
    },
  ],
};
